server {
    listen      80;
    server_name _;
    server_tokens off;

    access_log /var/log/nginx/access.log;
    error_log  /var/log/nginx/error.log;

    location / {
        fastcgi_pass  app:9000;
        fastcgi_index index.php;
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/index.php;
    }
}
